# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141f1c43994459762c73be383758b69b6e09b5eded104364a8e0beb0951e0c597b5531ab8d676633ce6b4adb0b681284b459bf80cc8703ec31a3313950e385aa

test:
  secret_key_base: 06bab8661154497383ae698748e5b81ab2968ce5bd251766c83e498a25c9d3e50870e2895b63323686848d278a1785ac0cbb4f257290218dacdb6b7ad26ec876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
